general_cfg:
  algo_name: DQN
  device: cpu
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: tasks
  mode: train
  
  save_fig: true
  seed: 3
  show_fig: false
  max_episode: -1
  max_step: 200
  wrapper: null
  n_interactors: 1
algo_cfg:
  batch_size: 64
  buffer_size: 40000
  epsilon_decay: 800
  epsilon_end: 0.01
  epsilon_start: 0.99
  gamma: 0.99
  lr: 0.01
  target_update: 4
  value_layers:
    - layer_type: linear
      layer_size: [256]
      activation: relu
    - layer_type: linear
      layer_size: [256]
      activation: relu
env_cfg:
  id: MountainCar-v0
  render: null