general_cfg:
  algo_name: DDPG
  device: cpu
  env_name: HalfCheetah-v3
  eval_eps: 10
  eval_per_episode: 100
  load_checkpoint: false
  load_path: tasks
  max_steps: 200
  mode: train
  mp_backend: mp
  new_step_api: true
  render: false
  render_mode: rgb_array
  save_fig: true
  seed: 0
  show_fig: false
  test_eps: 20
  train_eps: 5000
  wrapper: null
algo_cfg:
  actor_hidden_dim: 300
  actor_lr: 0.0001
  batch_size: 128
  buffer_size: 1000000
  critic_hidden_dim: 300
  critic_lr: 0.001
  gamma: 0.99
  tau: 0.005
